version: "3.8"
services:
  ezshield:
    network_mode: host
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    env_file:
      - .env
    logging:
      options:
        max-size: "12m"
        max-file: "5"
    command:
      - start-worker
    volumes:
      - ezshield:/root
volumes:
  ezshield: